### ISSUE TITLE
Thread System Messages Do Not Display in Transcript

### ISSUE THREAD

**Issue by Zennara** [mahtoid/DiscordChatExporterPy#87] opened 2023-06-20 23:10 UTC
### DiscordChatExporterPy Version

2.5.3

### Discord Version

PyCord 2.4.1

### Bug Description

System messages removing or adding users to threads do not properly display and instead show blank messages in the transcript.

### Additional Information

![image](https://github.com/mahtoid/DiscordChatExporterPy/assets/64995253/679077e3-40a0-4e43-8e22-4939bf2e4d01)

**Comment by mahtoid** [comment] 2023-06-22 20:49
Hey! I have written this down to solve in the next version. Thank you so much for the report.

I will leave this ticket open until the issue gets solved.

**Comment by mahtoid** [comment] 2023-06-24 12:41
@Zennara although the API supports it - there is no 'Join Thread' system message anymore is there? There is only the remove thread system message

**Comment by Zennara** [comment] 2023-06-24 12:48
@mahtoid I believe it is `recipient_add` and `recipient_remove` 
https://discordpy.readthedocs.io/en/stable/search.html?q=recipient_add

**Comment by Zennara** [comment] 2023-06-24 12:49
Scratch that, I'm too tired, I'm not actually sure

**Comment by Zennara** [comment] 2023-06-24 12:54
![image](https://github.com/mahtoid/DiscordChatExporterPy/assets/64995253/d7a07a66-feb2-498f-a138-69e1d013fb2b)
I'm unable to test right now but it may be only an issue with removing and adding members to **private** threads. I haven't explicitly tested public thread join messages. I'm not sure there even is a system message for joining a thread. Only adding and removing members in a private thread. I should have clarified.

**Comment by MichaelDavidGK** [comment] 2023-06-24 13:23
> ![image](https://user-images.githubusercontent.com/64995253/248478456-d7a07a66-feb2-498f-a138-69e1d013fb2b.png) I'm unable to test right now but it may be only an issue with removing and adding members to **private** threads. I haven't explicitly tested public thread join messages. I'm not sure there even is a system message for joining a thread. Only adding and removing members in a private thread. I should have clarified.

The issue is we tried private threads and adding people with mentioning them @ doesn't give msg
How are you adding people to threads?

**Comment by mahtoid** [comment] 2023-06-24 13:37
@Zennara if you can send me across the SVG for the 'Thread Add' icon (Ctrl + Shift + I) then click on the element and copy the link - then I'll get it all added and sorted. As @MichaelDavidGK unable to prompt the 'join' system message from private threads, but everything is setup for it.

**Comment by MichaelDavidGK** [comment] 2023-06-24 13:44
You need dev tools enabled if you didn't enable it before
There is an option in better discord to do so
Discord canary and ptb have it enabled
If you don't have either of these then you need to enable it by editing %appdata%/discord/settings.json
Add this anywhere:
> "DANGEROUS_ENABLE_DEVTOOLS_ONLY_ENABLE_IF_YOU_KNOW_WHAT_YOURE_DOING": true,

example:
![image](https://github.com/mahtoid/DiscordChatExporterPy/assets/39009683/f224fdc7-0d36-4623-8ef6-fb74b7c867ae)

Feel free to disable it afterwards

**Comment by Zennara** [comment] 2023-06-25 02:37
@mahtoid 
https://discord.com/assets/d1382af8d9e755bc44811b1fd92990a8.svg
https://discord.com/assets/f772d3d7eddcf3c84f710c10999479f0.svg

**Comment by Zennara** [comment] 2023-06-25 02:38
@MichaelDavidGK 
A bot is adding them to the thread via the API call, not directly mentioning the user.

**Comment by MichaelDavidGK** [comment] 2023-06-25 02:42
> @MichaelDavidGK A bot is adding them to the thread via the API call, not directly mentioning the user.

ohhh, ye i thought i seen it somewhere but couldn't find it
Matt will probably release it soon since you sent assets :D

**Comment by mahtoid** [comment] 2023-07-11 19:39
Closing this issue as the update has now been release. Please keep in mind there will be a hot fix coming out soon though to solve the markdown reversing issue on code blocks.

**Closed by mahtoid** 2023-07-11 19:39 UTC
Labels: bug
