### ISSUE TITLE
Issue while exporting

### ISSUE THREAD

**Issue by Classified154** [mahtoid/DiscordChatExporterPy#24] opened 2021-12-21 16:03 UTC
![image](https://user-images.githubusercontent.com/53806655/146961072-4d155d03-32f4-4485-a77f-6375c1c7d7e5.png)

**Comment by mahtoid** [comment] 2021-12-21 16:13
Hey @Classified154 - sorry you're having an issue.

Could you let me know what version or fork of `discordpy` you are using - along with what version of `chat-exporter`?

**Comment by mahtoid** [comment] 2021-12-21 16:38
I'm closing this issue as we've solved this on Discord.

To anyone else who has a similar issue, this is caused by using `disnake` on the `chat-exporter` version of `1.7.2`.
The solution (for now) would be to use the dev branch of `chat-exporter` being `reconstruct`.

```
I'd recommend doing: `pip uninstall chat-exporter` then add `git+https://github.com/mahtoid/DiscordChatExporterPy@reconstruct` to your `requirements.txt` 
 --- or alternatively do `pip install git+https://github.com/mahtoid/DiscordChatExporterPy@reconstruct` (again after you uninstall the `pypi` version)

This is a development branch, so there may be a couple of issues which I'm solving currently - but it gives support for `disnake`
```

I will be looking to merge this version in to `master` at the start of the new year once all the minor bugs have been discovered and solved.

**Closed by mahtoid** 2021-12-21 16:38 UTC
Labels: bug
