### ISSUE TITLE
Error when exporting

### ISSUE THREAD

**Issue by apilol** [mahtoid/DiscordChatExporterPy#78] opened 2023-02-15 05:08 UTC
### DiscordChatExporterPy Version

2.5.0

### Discord Version

Pycord: 2.3.3

### Bug Description

![image](https://user-images.githubusercontent.com/110469682/218937501-39ee32a1-d861-451e-b05c-108b735b164e.png)

That happens when I try and run the command

### Bug Traceback

Traceback (most recent call last):
  File "C:\Users\xrkzl\AppData\Roaming\Python\Python310\site-packages\chat_exporter\construct\transcript.py", line 164, in export
    return await super().build_transcript()
  File "C:\Users\xrkzl\AppData\Roaming\Python\Python310\site-packages\chat_exporter\construct\transcript.py", line 55, in build_transcript
    message_html, meta_data = await gather_messages(
  File "C:\Users\xrkzl\AppData\Roaming\Python\Python310\site-packages\chat_exporter\construct\message.py", line 389, in gather_messages
    content_html, meta_data = await MessageConstruct(
  File "C:\Users\xrkzl\AppData\Roaming\Python\Python310\site-packages\chat_exporter\construct\message.py", line 83, in construct_message
    await self.build_message()
  File "C:\Users\xrkzl\AppData\Roaming\Python\Python310\site-packages\chat_exporter\construct\message.py", line 87, in build_message
    await self.build_content()
  File "C:\Users\xrkzl\AppData\Roaming\Python\Python310\site-packages\chat_exporter\construct\message.py", line 135, in build_content
    self.message.content = await fill_out(self.guild, message_content, [
  File "C:\Users\xrkzl\AppData\Roaming\Python\Python310\site-packages\chat_exporter\ext\html_generator.py", line 26, in fill_out
    v = await ParseMention(v, guild).flow()
  File "C:\Users\xrkzl\AppData\Roaming\Python\Python310\site-packages\chat_exporter\parse\mention.py", line 54, in flow
    await self.time_mention()
  File "C:\Users\xrkzl\AppData\Roaming\Python\Python310\site-packages\chat_exporter\parse\mention.py", line 144, in time_mention
    timezone = pytz.timezone(self.guild.timezone)
AttributeError: 'Guild' object has no attribute 'timezone'
Please send a screenshot of the above error to https://www.github.com/mahtoid/DiscordChatExporterPy

**Comment by mahtoid** [comment] 2023-02-16 09:19
Hello @apilol - are you passing in any additional arguments (other than `TextChannel`) in to the `chat_exporter` function? If so you will need to use kwargs, for example:

```
transcript = await chat_exporter.export(
        ctx.channel,
        limit=limit,
        tz_info=tz_info,
        military_time=military_time,
        bot=bot,
    )
```

A full list along with expected types is displayed on the README. 

---

Let me know if that solves your issue, or whether there is something else going on here.

**Comment by apilol** [comment] 2023-02-16 10:32
No but I managed to fix it by downgrading chat_exporter versions.

**Comment by mahtoid** [comment] 2023-02-16 17:38
Weird. I'll take a look in to this at the weekend and find out what is going on. Will update this issue then.

**Comment by mahtoid** [comment] 2023-02-18 12:26
@apilol I'm unable to reproduce the issue, however I have added a default to use just in case it fails to set `timezone` attribute on to guild object originally for whatever reason.

This is currently in the `2.6.0` branch, which you can clone locally and use from. I am currently unsure on when this will see release.

Closing out the issue with pending release, feel free to re-open if it does not solve; or create another issue for any other bugs you may find

💜

**Closed by mahtoid** 2023-02-18 12:26 UTC
Labels: bug
